services:
    postgres:
        image: "postgres:15"
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            TZ: UTC
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        volumes:
            - "postgres:/var/lib/postgresql/data"
            - "./docker/postgres/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql"
        networks:
            - maple-network
        healthcheck:
            test:
                [
                    "CMD",
                    "pg_isready",
                    "-q",
                    "-d",
                    "${DB_DATABASE}",
                    "-U",
                    "${DB_USERNAME}",
                ]
            retries: 3
            timeout: 5s
    redis:
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "redis:/data"
        networks:
            - maple-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    minio:
        build: ./docker/minio
        image: "autumn/minio:${APP_VERSION}"
        ports:
            - "${FORWARD_MINIO_PORT:-9000}:9000"
            - "${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900"
        environment:
            MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
            MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
        volumes:
            - "minio:/data/minio"
            - "./docker/minio/export:/export"
        networks:
            - maple-network
        healthcheck:
            test: ["CMD", "mc", "ready", "local"]
            retries: 3
            timeout: 5s

networks:
    maple-network:
        driver: bridge
        name: maple-network
volumes:
    postgres:
    redis:
    minio:
